# all commands by default will run on every push, not every commit
default_install_hook_types: [pre-push]
default_stages: [commit]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.1
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-core>=1.9.2',
          'dbt-snowflake==1.9.0',
          'sqlfluff-templater-dbt==3.3.1'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-core>=1.9.2',
          'dbt-snowflake==1.9.0',
          'sqlfluff-templater-dbt==3.3.1'
        ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.2.1
    hooks:
      # - id: dbt-docs-generate
      # - id: check-source-table-has-description
      # - id: check-model-columns-have-desc
      # - id: check-model-has-all-columns
      #   args: ["--manifest", "path/to/manifest.json", "--"]
      - id: check-model-has-tests
        args: ["--test-cnt", "2", "--"]
