[project]
name = "poutineshop-public"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.9.2",
    "dbt-coverage==0.2.2",
    "dbt-snowflake>=1.9.0",
    "pre-commit==2.18.1",
]
